### PR TITLE
Added Admin functionality

### LINKED ISSUE #15: Implement Admin Login/Registration and Feedback Management System
# Description

We need to create a secure admin login/registration page for Notesphere. This page should only be accessible via a manually entered route (i.e., not accessible through navigation links or UI components to ensure heightened security). The design of the login page should align with the current aesthetic of Notesphere while being distinct enough to indicate it’s for admin access.

Upon successful login, the admin should gain access to a hidden "Dashboard" link in the navigation bar, appearing beside the "About" section. This page will display all feedback submitted by non-admin users, organized in reverse chronological order (newest feedback first).

Admins should not have access to the main homepage used by non-admin users. This functionality is essential for maintaining administrative control while ensuring regular users have a distinct experience.

- Requirements:

- A dedicated admin login/register page only accessible through a direct route.
- Admin-exclusive "Dashboard" page on the navbar displaying user feedback.
- Sorted feedback by date (most recent first).
- Admin restricted from accessing the main user homepage.
- All frontend changes in alignment with current look of Notesphere but not a copy.

### PR DESCRIPTION
**Pull request by Manish-Sharma26**
## Description

This PR introduces a full admin functionality feature for Notesphere, which includes:

- Admin login and registration pages that are only accessible through manually entered routes.
- Admin dashboard that shows all feedback from non-admin users in reverse chronological order.
- Security features that prevent admins from accessing the user homepage, ensuring separation of admin and user roles.
- Changes made to the frontend are aligned with the Notesphere design, but are distinct to indicate the admin area.
- Added two more features : search bar and summary statistics
### Summary of Changes

1. **Admin Authentication Middleware (`middleware/adminAuth.js`):**
   - Created middleware to ensure only authenticated admin users can access specific routes.
   - Returns a `403 - Access Denied` response for non-admin users.

2. **Admin Authentication Routes (`routes/adminAuth.js`):**
   - **Registration Route (`POST /api/admin/register`):** Allows existing admins to create new admin users with encrypted passwords.
   - **Login Route (`POST /api/admin/login`):** Authenticates admin credentials and returns a JWT token upon successful login.

3. **Admin Dashboard Routes (`routes/adminDashboard.js`):**
   - **Get All Notes (`GET /api/admin/notes`):** Retrieves all user notes, sorted by date, accessible only to admins.
   - **Fetch Note Image (`GET /api/admin/fetchimagenote/:id`):** Retrieves images associated with notes, restricted to admin users.

4. **App Structure (`App.js`):**
   - Integrated admin authentication routes.
   - Implemented protected routes for both home and admin dashboard.
   - Created `ProtectedHome` and `ProtectedAdminDashboard` components to redirect users based on their authentication status.

5. **Admin Dashboard (`AdminDashboard.js`):**
   - Fetched all notes for admin review using Axios.
   - Added image retrieval for each note.
   - Implemented search functionality to filter notes by tag.
   - Created Bar and Pie charts using Chart.js to display statistics on notes per tag and distribution by user.

6. **Admin Login (`AdminLogin.js`):**
   - Implemented admin login functionality.
   - Redirects to the admin dashboard upon successful login.

7 **Admin Registration (`AdminRegister.js`):**
   - Created registration form for new admin users.
   - Redirects to the admin dashboard after successful registration.

8 **Navbar Component (`Navbar.js`):**
   - Updated navigation to include admin dashboard link.
   - Adjusted visibility of navigation links based on user roles (admin vs. regular user).
   - Handled logout behavior with role-based redirection.
9** AuthContext.js**
- Created an authentication context using `createContext`.

10**AuthState.js**
- Implemented the `AuthState` component to manage authentication state.

These changes collectively enhance the admin functionality and security of the application, providing a clear separation between regular user and admin features.

## Related Issue

Fixes #15

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Motivation and Context

This change is required to add a secure and efficient way for admins to manage feedback, providing an admin-only dashboard while ensuring that admins and regular users have separate experiences. It also enhances the platform’s security by making the admin pages inaccessible via navigation, accessible only through a direct route.

## How Has This Been Tested?

- Admin login and registration functionality was tested manually, ensuring admins can access the dashboard while regular users cannot.
- Tested the hidden admin route by verifying the login and registration forms are not accessible through standard navigation.
- Verified that feedback is displayed in reverse chronological order on the admin dashboard.
- Ensured that admins cannot access the user homepage, reinforcing the role separation.
  
Testing environment:
- **Browser**: Chrome
- **Platform**: Windows 10, MacOS
- **React version**: 18.x

## Checklist:

- [x] I have registered myself at [Contrihub website](https://sac.mnnit.ac.in/contrihub).
- [x] My code follows the code style of this project.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] My changes generate no new warnings.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

**Test Configuration**:
* Firmware version: N/A
* Hardware: N/A
* Toolchain: N/A
* SDK: N/A

### CODE REVIEW

**Comment by Manish-Sharma26** [comment]
Only existing admin can create new admin so one of the admin is:
admin@gmail.com and 51555155
I have created the pr but as the contrihub webiste is not working so i am not able to submit it on the contrihub

**Comment by shubhankertiwari8** [comment]
@Manish-Sharma26 This functionality is not needed as only people who know the route to admin register/login page will be able to access it and it is sufficient for security so remove this need for another admin to create a new admin

**Comment by Manish-Sharma26** [comment]
Okay, I will remove this feature

**Comment by Manish-Sharma26** [comment]
I have removed that admin existence thing ,so please review now.
And please accept my issue request again so that i can add my pr link in the contrihub.

**Pull request merged**
