### PR TITLE
Added Attachment and confirm modal

### LINKED ISSUE #4: Expanded Requirements for the Feedback Edit Modal
# Description

### To enhance the functionality of the feedback card edit feature, we can introduce a modal that allows the user to edit the original feedback details, such as the title and description. The modal should display two input fields labeled "Title" and "Description" when the user clicks on the edit icon located at the top right corner of the feedback card. The user can then modify the content and save the changes using a "Save Changes" button.

Additionally, to improve the user experience, the modal will automatically close if the user clicks anywhere outside the modal, providing a more intuitive interaction. Here's how we can expand and frame this:

1. **Modal Activation**:

- When the user clicks on the edit icon at the top right corner of the feedback card, a modal should be triggered.
- This modal will be centered on the screen and display two labeled input fields:
- Title: An editable field allowing the user to update the feedback title.
- Description: A larger text area allowing the user to update the feedback description.

2. **Input Labels**:

- Ensure the "Title" and "Description" labels are clearly visible and aligned with their corresponding input fields.
- Users can easily update the original title and description provided when the feedback was first submitted.

3. **Save Changes Button**:

- At the bottom of the modal, include a "Save Changes" button that, when clicked, updates the feedback with the newly edited values.
- Upon clicking, the modal should close, and the updated feedback should be reflected on the card.

4. **Modal Dismissal**:

- If the user clicks anywhere outside the modal (on the screen), the modal should automatically close. This provides a more natural and user-friendly interaction, especially if the user changes their mind about editing.
- This functionality can be achieved by adding an event listener for clicks outside the modal area.

5. **Edge Case Handling**:

- If no changes are made and the user clicks "Save Changes", the modal should still close, but no update should be performed on the original feedback.
- Ensure that input validation is in place, such as preventing empty fields for required input like the title.

6. **Character Counter**

- Add a character counter for the title and description fields to limit the length of input and give users real-time feedback on how much space they have left.
- You can highlight the counter in red when the user approaches or exceeds the limit.

7. **Attach Media**

- Allow users to attach images, screenshots, or files when editing feedback. This could give more context to the feedback.

8. **Add a cancel button on top right corner of modal and fix css**

### PR DESCRIPTION
**Pull request by Manish-Sharma26**
<!--- Provide a general summary of your changes in the Title above -->

## Description

<!--- Describe your changes in detail -->

This pull request introduces two significant features to the NoteSphere project:

### 1. Attachment (Image Upload) Functionality:

#### Backend Enhancements:
- **Schema Update**: 
  - Added `imageData` (Buffer) and `contentType` (String) fields to the Notes schema in `backend/models/Notes.js` to store binary image data and its MIME type.
  
- **Multer Integration**: 
  - Configured Multer in `backend/index.js` and `backend/routes/notes.js` for handling image uploads with memory storage. 
  - This setup ensures efficient handling and validation of image files (restricting to image MIME types and limiting file size to 5MB).
  
- **API Endpoints**:
  - **Update Note**: Modified the `PUT /updatenote/:id` route to accept and process image uploads.
  - **Fetch Image**: Added a new `GET /fetchimagenote/:id` route to retrieve and serve the stored images for individual notes.

#### Frontend Enhancements:
- **State Management**:
  - Updated the `Notes` component (`src/components/Notes.js`) and `Noteitem` component (`src/components/Noteitem.js`) to handle image data, including uploading and displaying images associated with notes.
  
- **Image Compression**:
  - Integrated `browser-image-compression` to optimize image sizes before uploading, enhancing performance and reducing storage requirements.

- **UI Updates**:
  - Modified forms to include file input fields for image uploads and updated the display logic to render images within notes.

### 2. Confirmation Modal for Editing Notes:

- **Modal Implementation**:
  - Added a confirmation modal in the `Notes` component to prompt users before finalizing the edit of a note. This ensures that users intentionally make changes, reducing accidental modifications.

- **UX Improvements**:
  - Utilized Bootstrap modals for a seamless and consistent user experience, allowing users to confirm or cancel their edit actions effectively.

### Related Changes:

#### Dependencies:
- Added `multer` for handling `multipart/form-data` (file uploads).
- Included `browser-image-compression` for client-side image optimization.

#### Error Handling:
- Enhanced error handling in the backend to manage Multer-specific errors and other potential issues during file uploads.


<!--- This project only accepts pull requests related to open issues -->
<!--- If suggesting a new feature or change, please discuss it in an issue first -->
<!--- If fixing a bug, there should be an issue describing it with steps to reproduce -->
<!--- Please link to the issue here: -->

Fixes #4

## Type of change

<!--- What types of changes does your code introduce? Put an `x` in all the boxes that apply: -->

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Motivation and Context

Enhancing the NoteSphere application with image attachment capabilities allows users to enrich their notes with visual content, improving the overall utility and user experience. The addition of a confirmation modal ensures better user interaction by preventing unintended edits.

## How Has This Been Tested?

<!--- Please describe in detail how you tested your changes. -->
<!--- Include details of your testing environment, and the tests you ran to -->
<!--- see how your change affects other areas of the code, etc. -->
<!-- Ignore if not relevant for you -->

###Backend:
-Tested image upload and retrieval endpoints using Postman to ensure proper handling and storage of image data.
-Verified error responses for invalid file types and oversized uploads.
###Frontend:
-Manually tested the image upload process through the UI, ensuring images are correctly displayed within notes.
-Verified the functionality of the confirmation modal during the note editing process.
-Ensured compatibility across different browsers and devices.

## Screenshots (if appropriate):
<img width="938" alt="note" src="https://github.com/user-attachments/assets/44055147-66b5-488e-9007-4001f747878c">

## Checklist:

<!--- Go over all the following points, and put an `x` in all the boxes that apply. -->
<!--- If you're unsure about any of these, don't hesitate to ask. We're here to help! -->

- [x] I have registered myself at [Contrihub website](https://sac.mnnit.ac.in/contrihub).
- [x] My code follows the code style of this project.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.


**Test Configuration**:
* Firmware version:N/A
* Hardware:N/A
* Toolchain:Node.js, Express.js, React.js
* SDK:N/A

### CODE REVIEW

**Review by shubhankertiwari8 — CHANGES_REQUESTED** [review]
The changes have been made in old version of notesphere ui has been changed so make sure to pull the changes and then implement your functionalities

**Comment by Manish-Sharma26** [comment]
I have pulled all previous code and added the functionality ,could you please review now

**Comment by shubhankertiwari8** [comment]
The image appearing on uploading seems to work fine just work on appearance a bit so that image looks good while appearing for example it can appear in center rather then on left and also css of modal needs to be changed it should look like a part of project and you may get bonus points if you improve appearance of feedback card so that description of title and 
description appear differently like adding header footer or using bold font for title.

**Comment by Manish-Sharma26** [comment]
I have done some changes.(I have added date feature also)
Here are the screenshots of the same
note3

note2
Please review this

**Comment by shubhankertiwari8** [comment]
Looks fine create a PR

**Comment by Manish-Sharma26** [comment]
I have to create a new pr ?

**Comment by shubhankertiwari8** [comment]
ofcourse

**Comment by Manish-Sharma26** [comment]
But i have already submitted the previous pr link  in the contrihub, so please consider it

**Comment by shubhankertiwari8** [comment]
create pr here then only i will be able to merge your changes in repo dont make another PR on portal

**Comment by Manish-Sharma26** [comment]
Okay .
Created the pr

**Pull request merged**
