### PR TITLE
Fixed to show home button only if logged in

### PR DESCRIPTION
**Pull request by krVatsal**
Used the local storage saved token to verify if the user is logged in or not, if the token is there it will show home button otherwise it will not show the buttons.

### CODE REVIEW

**Comment by shubhankertiwari8** [comment]
@krVatsal Have you created a PR on portal? If not so do it.

**Comment by krVatsal** [comment]
@shubhankertiwari8 sir there's no blank space in the portal where I could put my PR link

**Comment by krVatsal** [comment]
Screenshot_2024-10-12-16-52-59-93_40deb401b9ffe8e1df2f1cc5ba480b12

**Comment by shubhankertiwari8** [comment]
@krVatsal Please create a PR verification request on portal otherwise i wont be able to merge your PR

**Comment by krVatsal** [comment]
@shubhankertiwari8 can you please reassign it to me such that i can put the link there as it's not showing in active issues

**Pull request closed without merging**
