### PR TITLE
feature/announcement page

### LINKED ISSUE #22: Announcement Page
# Description

Create a new page accessible through the navbar named **"Announcements"**, where admins can post important announcements, and users can view them in real-time. Only the admin will have permission to create and post announcements, while users can only read them. The announcements should be sorted chronologically by date and time (most recent at the top) and remain permanently visible unless manually removed by the admin.

### Admin Posting:
- Admins can post announcements on the **"Announcements"** page, which will immediately appear for all users in real-time.
- Before an announcement is posted, the admin should have an option to confirm and review the content before publishing.

### Real-Time Updates:
- The page should update in real-time, so users can see new announcements as soon as they are posted, without needing to refresh the page.
- Users should be notified of any new, unread announcements with a clear indication (e.g., a notification badge on the "Announcements" page link in the navbar).

### User View:
- Users can only read the announcements and cannot post or edit them.
- Announcements should be permanently stored and visible to all users unless manually removed by the admin.
- Announcements should be sorted in descending order of date and time, ensuring the most recent announcements appear at the top.

This feature is intended to create a centralized place for admins to share important updates, announcements, and notifications with users in real-time. Users need to be informed immediately when a new announcement is posted and have a clear way to distinguish between read and unread announcements.

Providing a real-time, permanent announcement page ensures that important information from the admin is effectively communicated to all users. It also prevents users from missing important updates by ensuring that unread announcements are highlighted.

### Announcement Page:
- Admins can post and manage announcements.
- Users can view announcements but cannot interact or post themselves.

### Real-Time Notifications:
- Users should see real-time updates when new announcements are posted, and there should be a clear indicator of unread announcements (e.g., a badge or highlight in the navbar).

### Chronological Sorting:
- Announcements should be sorted by date and time, with the newest appearing at the top of the page.

We considered creating a notification system or integrating announcements with other forms of communication, but a dedicated page keeps all updates in one clear and accessible place.

### PR DESCRIPTION
**Pull request by Gprakhar141**
## Description

I have implemented the Announcement Page where the admin can add or delete announcements and others users can read those announcements.
The announcements get modified on the frontend in real time using socket.js

Route for announcements page `http://localhost:3000/announcements`

## Related Issue

Fixes #22 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Motivation and Context

It provides facility to the admin to broadcast certain important information on the announcement page to all the users at once.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Screenshots (if appropriate):

https://github.com/user-attachments/assets/5f59db5c-c29f-4bcc-ad81-be51628dba8d

## Checklist:

- [x] I have registered myself at [Contrihub website](https://sac.mnnit.ac.in/contrihub).
- [x] My code follows the code style of this project.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by Gprakhar141** [comment]
@shubhankertiwari8 Sir please accept the PR on the website too.

**Comment by shubhankertiwari8** [comment]
can you share a video demonstration

**Comment by Gprakhar141** [comment]
@shubhankertiwari8 Sir I have added the video demonstration in the PR description. Sorry for being late as I was travelling. Please review it.

**Comment by shubhankertiwari8** [comment]
@Gprakhar141 only admin should be able to send announcement or delete it and announcement page should be accessible only after login

**Comment by Gprakhar141** [comment]
@shubhankertiwari8 Yes sir I have implemented the same but I just noticed that I had mistankenly reverted the changes made in index.js(main backend server file) alongwith db.js before committing changes. That's why it was not working properly. Sorry for this blunder. Maybe I should raise another PR with the correct changes.

I had completed it in time but just reverted index.js in the PR by mistake.

**Comment by Gprakhar141** [comment]
Whenever a normal user tries to add or delete an announcement, the server responds with a status 403(forbidden).

**Comment by Gprakhar141** [comment]
> @Gprakhar141 only admin should be able to send announcement or delete it and announcement page should be accessible only after login

Sir I have fixed it, the buttons don't get displayed for non-admins. Previously the backend sent forbidden 403 for non-admins but the buttons were still visible on the frontend.

**Comment by Gprakhar141** [comment]
@shubhankertiwari8 please respond sir.

**Comment by shubhankertiwari8** [comment]
@Gprakhar141 do it as you want if you know the error resolve it and make a new pr

**Comment by Gprakhar141** [comment]
@shubhankertiwari8 ok sir

**Comment by Gprakhar141** [comment]
@shubhankertiwari8 Sir I have raised a new PR please check it.

**Pull request merged**
